apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: hub-of-hubs-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-of-hubs-operator
  namespace: system
  labels:
    name: hub-of-hubs-operator
spec:
  selector:
    matchLabels:
      name: hub-of-hubs-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: hub-of-hubs-operator
      labels:
        name: hub-of-hubs-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /hub-of-hubs-operator
        args:
        - --leader-elect
        image: controller:latest
        name: hub-of-hubs-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: hub-of-hubs-operator
      terminationGracePeriodSeconds: 10
