kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-agent
rules:
- apiGroups:
  - "hub-of-hubs.open-cluster-management.io"
  resources:
  - configs
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "app.k8s.io"
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  - managedclustersets
  - managedclustersetbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  - managedclustersets/bind
  verbs:
  - create
  - delete
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  - placementdecisions
  - placementdecisions/finalizers
  - placements
  - placements/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
