apiVersion: v1
kind: Service
metadata:
  labels:
    name: hub-of-hubs-operator
  name: hub-of-hubs-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: hub-of-hubs-operator