# permissions for end users to view configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-viewer-role
rules:
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - configs/status
  verbs:
  - get
