---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
