apiVersion: hubofhubs.open-cluster-management.io/v1alpha1
kind: Config
metadata:
  name: hub-of-hubs-config
  namesapce: open-cluster-management
spec:
  global:
    aggregationLevel: full
    heartbeatInterval:
      hoh: 60
      leafHub: 60
    enableLocalPolicies: true
  components:
    core:
      hoh:
        nonk8sAPI:
          basePath: /multicloud/hub-of-hubs-nonk8s-api
        rbac: {}
        specSync: {}
        statusSync:
          syncInterval: 5
        specTransportBridge:
          syncInterval: 5
          msgCompressType: gzip
          msgSizeLimit: 940  # KB unit, should < 1024(MB)
        statusTransportBridge:
          committerInterval: 40
          statisticsLogInterval: 0 # <=0 disable the statistics log
      leafHub:
        specSync:
          kubeClientPoolSIze: 10
          enforceHoHRbac: true
        statusSync:
          syncIntervalConfig:
             managedClusters: 5
             policies: 5
             controlInfo: 3600
          deltaSentCountSwitchFactor: 100
          msgCompressType: gzip
          msgSizeLimit: 940  # KB unit, should < 1024(MB)
    transport:
      provider: kafka
      kafka:
         version: 2.7.0
         replicas: 3
      syncService:
         version: stable
         pollingInterval: 5
    database:
      provider: postgresql
      postgresql:
        version: 13.4.1
        enableHA: true

