namespace: open-cluster-management

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
- crd/hubofhubs.open-cluster-management.io_configs.yaml

images:
- name: hub-of-hubs-operator
  newName: quay.io/morvencao/hub-of-hubs-operator
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

