apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-of-hubs-manager
  namespace: open-cluster-management
  labels:
    name: hub-of-hubs-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hub-of-hubs-manager
  template:
    metadata:
      labels:
        name: hub-of-hubs-manager
    spec:
      serviceAccountName: hub-of-hubs-manager
      containers:
        - name: hub-of-hubs-manager
          image: {{.Registry}}/hub-of-hubs-manager:{{.ImageTag}}
          imagePullPolicy: Always
          args:
            - --zap-devel=true
            - --manager-namespace=$(POD_NAMESPACE)
            - --watch-namespace=$(WATCH_NAMESPACE)
            - --transport-type={{.TransportType}}
            - --process-database-url=$(PROCESS_DATABASE_URL)
            - --transport-bridge-database-url=$(TRANSPORT_BRIDGE_DATABASE_URL)
            - --authorization-cabundle-path=/hub-of-hubs-rbac-ca/service-ca.crt
            - --cluster-api-cabundle-path=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --server-certificate-path=/certs/tls.crt
            - --server-key-path=/certs/tls.key
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
            - name: PROCESS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hub-of-hubs-database-secret
                  key: url
            - name: TRANSPORT_BRIDGE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hub-of-hubs-database-transport-bridge-secret
                  key: url
          volumeMounts:
            - readOnly: true
              mountPath: /hub-of-hubs-rbac-ca
              name: hub-of-hubs-rbac-ca
            - readOnly: true
              mountPath: /certs
              name: certs
      volumes:
        - name: hub-of-hubs-rbac-ca
          configMap:
            name: hub-of-hubs-rbac-ca-bundle
        - name: certs
          secret:
            secretName: hub-of-hubs-manager-certs
