kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-manager
  namespace: open-cluster-management
  labels:
    name: hub-of-hubs-manager
subjects:
- kind: ServiceAccount
  name: hub-of-hubs-manager
roleRef:
  kind: Role
  name: hub-of-hubs-manager
  apiGroup: rbac.authorization.k8s.io
