//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsConfig) DeepCopyInto(out *ComponentsConfig) {
	*out = *in
	if in.Core != nil {
		in, out := &in.Core, &out.Core
		*out = new(CoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(TransportConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsConfig.
func (in *ComponentsConfig) DeepCopy() *ComponentsConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigList) DeepCopyInto(out *ConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigList.
func (in *ConfigList) DeepCopy() *ConfigList {
	if in == nil {
		return nil
	}
	out := new(ConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalConfig)
		**out = **in
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(ComponentsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStatus) DeepCopyInto(out *ConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStatus.
func (in *ConfigStatus) DeepCopy() *ConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreConfig) DeepCopyInto(out *CoreConfig) {
	*out = *in
	if in.Hoh != nil {
		in, out := &in.Hoh, &out.Hoh
		*out = new(HohConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LeafHub != nil {
		in, out := &in.LeafHub, &out.LeafHub
		*out = new(LeafHubConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreConfig.
func (in *CoreConfig) DeepCopy() *CoreConfig {
	if in == nil {
		return nil
	}
	out := new(CoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Postgresql != nil {
		in, out := &in.Postgresql, &out.Postgresql
		*out = new(PostgreSqlConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	out.HeartbeatIntervals = in.HeartbeatIntervals
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatIntervals) DeepCopyInto(out *HeartbeatIntervals) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatIntervals.
func (in *HeartbeatIntervals) DeepCopy() *HeartbeatIntervals {
	if in == nil {
		return nil
	}
	out := new(HeartbeatIntervals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HohConfig) DeepCopyInto(out *HohConfig) {
	*out = *in
	if in.Nonk8sAPI != nil {
		in, out := &in.Nonk8sAPI, &out.Nonk8sAPI
		*out = new(Nonk8sAPIConfig)
		**out = **in
	}
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = new(RBACConfig)
		**out = **in
	}
	if in.SpecSync != nil {
		in, out := &in.SpecSync, &out.SpecSync
		*out = new(SpecSyncConfig)
		**out = **in
	}
	if in.StatusSync != nil {
		in, out := &in.StatusSync, &out.StatusSync
		*out = new(StatusSyncConfig)
		**out = **in
	}
	if in.SpecTransportBridge != nil {
		in, out := &in.SpecTransportBridge, &out.SpecTransportBridge
		*out = new(SpecTransportBridgeConfig)
		**out = **in
	}
	if in.StatusTransportBridge != nil {
		in, out := &in.StatusTransportBridge, &out.StatusTransportBridge
		*out = new(StatusTransportBridgeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HohConfig.
func (in *HohConfig) DeepCopy() *HohConfig {
	if in == nil {
		return nil
	}
	out := new(HohConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConfig) DeepCopyInto(out *KafkaConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConfig.
func (in *KafkaConfig) DeepCopy() *KafkaConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafHubConfig) DeepCopyInto(out *LeafHubConfig) {
	*out = *in
	if in.SpecSync != nil {
		in, out := &in.SpecSync, &out.SpecSync
		*out = new(LeafHubSpecSyncConfig)
		**out = **in
	}
	if in.StatusSync != nil {
		in, out := &in.StatusSync, &out.StatusSync
		*out = new(LeafHubStatusSyncConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafHubConfig.
func (in *LeafHubConfig) DeepCopy() *LeafHubConfig {
	if in == nil {
		return nil
	}
	out := new(LeafHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafHubSpecSyncConfig) DeepCopyInto(out *LeafHubSpecSyncConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafHubSpecSyncConfig.
func (in *LeafHubSpecSyncConfig) DeepCopy() *LeafHubSpecSyncConfig {
	if in == nil {
		return nil
	}
	out := new(LeafHubSpecSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafHubStatusSyncConfig) DeepCopyInto(out *LeafHubStatusSyncConfig) {
	*out = *in
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(LeafHubStatusSyncIntervalSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafHubStatusSyncConfig.
func (in *LeafHubStatusSyncConfig) DeepCopy() *LeafHubStatusSyncConfig {
	if in == nil {
		return nil
	}
	out := new(LeafHubStatusSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafHubStatusSyncIntervalSettings) DeepCopyInto(out *LeafHubStatusSyncIntervalSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafHubStatusSyncIntervalSettings.
func (in *LeafHubStatusSyncIntervalSettings) DeepCopy() *LeafHubStatusSyncIntervalSettings {
	if in == nil {
		return nil
	}
	out := new(LeafHubStatusSyncIntervalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nonk8sAPIConfig) DeepCopyInto(out *Nonk8sAPIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nonk8sAPIConfig.
func (in *Nonk8sAPIConfig) DeepCopy() *Nonk8sAPIConfig {
	if in == nil {
		return nil
	}
	out := new(Nonk8sAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSqlConfig) DeepCopyInto(out *PostgreSqlConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSqlConfig.
func (in *PostgreSqlConfig) DeepCopy() *PostgreSqlConfig {
	if in == nil {
		return nil
	}
	out := new(PostgreSqlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACConfig) DeepCopyInto(out *RBACConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACConfig.
func (in *RBACConfig) DeepCopy() *RBACConfig {
	if in == nil {
		return nil
	}
	out := new(RBACConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecSyncConfig) DeepCopyInto(out *SpecSyncConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecSyncConfig.
func (in *SpecSyncConfig) DeepCopy() *SpecSyncConfig {
	if in == nil {
		return nil
	}
	out := new(SpecSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecTransportBridgeConfig) DeepCopyInto(out *SpecTransportBridgeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecTransportBridgeConfig.
func (in *SpecTransportBridgeConfig) DeepCopy() *SpecTransportBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(SpecTransportBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusSyncConfig) DeepCopyInto(out *StatusSyncConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusSyncConfig.
func (in *StatusSyncConfig) DeepCopy() *StatusSyncConfig {
	if in == nil {
		return nil
	}
	out := new(StatusSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusTransportBridgeConfig) DeepCopyInto(out *StatusTransportBridgeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusTransportBridgeConfig.
func (in *StatusTransportBridgeConfig) DeepCopy() *StatusTransportBridgeConfig {
	if in == nil {
		return nil
	}
	out := new(StatusTransportBridgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncServiceConfig) DeepCopyInto(out *SyncServiceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncServiceConfig.
func (in *SyncServiceConfig) DeepCopy() *SyncServiceConfig {
	if in == nil {
		return nil
	}
	out := new(SyncServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportConfig) DeepCopyInto(out *TransportConfig) {
	*out = *in
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaConfig)
		**out = **in
	}
	if in.SyncService != nil {
		in, out := &in.SyncService, &out.SyncService
		*out = new(SyncServiceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportConfig.
func (in *TransportConfig) DeepCopy() *TransportConfig {
	if in == nil {
		return nil
	}
	out := new(TransportConfig)
	in.DeepCopyInto(out)
	return out
}
