/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/stolostron/hub-of-hubs-operator/apis/client/clientset/versioned"
	internalinterfaces "github.com/stolostron/hub-of-hubs-operator/apis/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/stolostron/hub-of-hubs-operator/apis/client/listers/hubofhubs/v1alpha1"
	hubofhubsv1alpha1 "github.com/stolostron/hub-of-hubs-operator/apis/hubofhubs/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentConfigInformer provides access to a shared informer and lister for
// AgentConfigs.
type AgentConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AgentConfigLister
}

type agentConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentConfigInformer constructs a new informer for AgentConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentConfigInformer constructs a new informer for AgentConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HubofhubsV1alpha1().AgentConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HubofhubsV1alpha1().AgentConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&hubofhubsv1alpha1.AgentConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hubofhubsv1alpha1.AgentConfig{}, f.defaultInformer)
}

func (f *agentConfigInformer) Lister() v1alpha1.AgentConfigLister {
	return v1alpha1.NewAgentConfigLister(f.Informer().GetIndexer())
}
