---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: spec
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-brokers-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: status
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-brokers-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
